### ISSUE TITLE
List of noticed issues to take in care

### ISSUE THREAD

**Issue by Valc** [infograf768/j4localise#10] opened 2021-08-20 21:55 UTC
Beta 2 version
I write it down here now that I have it fresh or I will forget it.
I'll try to get things off the list.

- The "Download package" button is only creating the files for "api" folder, and creating that files some fields such as "name" are not inserted.
- The field 'translation' does not store the selected files to include to create the language pack after 'Save'
- The button 'Import XML' do nothing with a console error 'Uncaught ReferenceError: jQuery is not defined'
- The button 'Import specific files' do nothing but no console error, simply seems that the modal window is not started
- The raw mode edition does not "parse" by javascript as before.
- The "context comments" that appear recently type **key="string" ; Here a comment is added**, they do not break anything when editing or saving the translation, but they are not displayed when translating and they seem to be useful.

**Comment by infograf768** [comment] 2021-08-25 10:09
@Valc 
1. This is what I get here for Download package, once unzipped

![Screen Shot 2021-08-25 at 11 41 45](https://user-images.githubusercontent.com/869724/130768167-58c4224b-2a52-4177-a084-d1219d176291.png)

What do you mean by "name" missing? we do have the 3 folders
```
	<files>
		<folder type="language" client="site" id="fr-FR">language/fr-FR</folder>
		<folder type="language" client="administrator" id="fr-FR">administrator/language/fr-FR</folder>
		<folder type="language" client="api" id="fr-FR">api/language/fr-FR</folder>
	</files>
```

2. Confirmed. Can't find for now where this comes from... IMPORTANT indeed

3 and 4. Both modals were solved

5 and 6: I guess these would be taken care of by your future PR for Issue https://github.com/infograf768/j4localise/issues/12

**Comment by Valc** [comment] 2021-08-29 05:16
@infograf768 
> Luckily, if you select all the files to include in the package and click on "Download", it will be generated without a problem. **The problem now is that if you hit "Save", that is lost**.

I've found it!
Arrrrrgh! With the test I have done, it is enough to write a book: I will go to the last: currently to "Save" we are passing along with each option selected from the "translations" field the "value" with the ".ini", and it is expected that that data goes without the ".ini", that is why the "value" sent from the "Save" never exactly coincide with those in the "value" of the HTML output of the "translations" field, which never have the ". ini ".

To be sure I had to modify the Joomla file in path /layouts/joomla/forms/field/groupedlist.php in this way:

```
<?php
/**
 * @package     Joomla.Site
 * @subpackage  Layout
 *
 * @copyright   (C) 2021 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\HTML\HTMLHelper;

extract($displayData);
//die(var_dump($displayData));
/**
 * Layout variables
 * -----------------
 * @var   string   $autocomplete    Autocomplete attribute for the field.
 * @var   boolean  $autofocus       Is autofocus enabled?
 * @var   string   $class           Classes for the input.
 * @var   string   $description     Description of the field.
 * @var   boolean  $disabled        Is this field disabled?
 * @var   string   $group           Group the field belongs to. <fields> section in form XML.
 * @var   boolean  $hidden          Is this field hidden in the form?
 * @var   string   $hint            Placeholder for the field.
 * @var   string   $id              DOM id of the field.
 * @var   string   $label           Label of the field.
 * @var   string   $labelclass      Classes to apply to the label.
 * @var   boolean  $multiple        Does this field support multiple values?
 * @var   string   $name            Name of the input field.
 * @var   string   $onchange        Onchange attribute for the field.
 * @var   string   $onclick         Onclick attribute for the field.
 * @var   string   $pattern         Pattern (Reg Ex) of value of the form field.
 * @var   boolean  $readonly        Is this field read only?
 * @var   boolean  $repeat          Allows extensions to duplicate elements.
 * @var   boolean  $required        Is this field required?
 * @var   integer  $size            Size attribute of the input.
 * @var   boolean  $spellcheck      Spellcheck state for the form field.
 * @var   string   $validate        Validation rules to apply.
 * @var   string   $value           Value attribute of the field.
 * @var   array    $groups          Groups of options available for this field.
 * @var   string   $dataAttribute   Miscellaneous data attributes preprocessed for HTML output
 * @var   array    $dataAttributes  Miscellaneous data attribute for eg, data-*
 */

$html = array();
$attr = '';
$test = '';
// Initialize some field attributes.
$attr .= !empty($class) ? ' class="form-select ' . $class . '"' : ' class="form-select"';
$attr .= !empty($size) ? ' size="' . $size . '"' : '';
$attr .= $multiple ? ' multiple' : '';
$attr .= $required ? ' required' : '';
$attr .= $autofocus ? ' autofocus' : '';
$attr .= $dataAttribute;
//die(var_dump($dataAttribute));
// To avoid user's confusion, readonly="true" should imply disabled="true".
if ($readonly || $disabled)
{
	$attr .= ' disabled="disabled"';
}

// Initialize JavaScript field attributes.
$attr .= !empty($onchange) ? ' onchange="' . $onchange . '"' : '';

// Create a read-only list (no name) with a hidden input to store the value.
if ($readonly)
{
	$html[] = HTMLHelper::_(
		'select.groupedlist', $groups, null,
		array(
			'list.attr' => $attr, 'id' => $id, 'list.select' => $value, 'group.items' => null, 'option.key.toHtml' => false,
			'option.text.toHtml' => false,
		)
	);

	// E.g. form field type tag sends $this->value as array
	if ($multiple && \is_array($value))
	{
		if (!\count($value))
		{
			$value[] = '';
		}

		foreach ($value as $val)
		{
			$html[] = '<input type="hidden" name="' . $name . '" value="' . htmlspecialchars($val, ENT_COMPAT, 'UTF-8') . '">';
		}
	}
	else
	{
		$html[] = '<input type="hidden" name="' . $name . '" value="' . htmlspecialchars($value, ENT_COMPAT, 'UTF-8') . '">';
	}
}

// Create a regular list.
else
{
	if ($multiple && \is_array($value))
	{
	    if ($multiple && \is_array($value))
	    {

        $newvalue = array();
		if (is_array($value))
		{
			    foreach ($value as $val)
			    {
                    $test .= "<br><b>Original value sended:></b> " . $val;
				    $newvalue[] = substr($val, 0, -4);
                    $test .= "<br><b>Real value to use:</b> " . substr($val, 0, -4);
                    $newvalue[] = $val;
			    }
		    }
	        $html[] = HTMLHelper::_(
		        'select.groupedlist', $groups, $name,
		        array(
			        'list.attr' => $attr, 'id' => $id, 'list.select' => $newvalue, 'group.items' => null, 'option.key.toHtml' => false,
			        'option.text.toHtml' => false,
		        )
	        );
        }
	}
    else
    {

	    $html[] = HTMLHelper::_(
		    'select.groupedlist', $groups, $name,
		    array(
			    'list.attr' => $attr, 'id' => $id, 'list.select' => $value, 'group.items' => null, 'option.key.toHtml' => false,
			    'option.text.toHtml' => false,
		    )
	    );
    }
}

echo implode($html) . "Test: <br>" . $test;
```
With this result:

![catched](https://user-images.githubusercontent.com/417247/131239279-96482a9b-1985-4336-83dd-91dc0f3afe58.png)


Of course we can't apply the solution by modifying the Joomla files, but now I know what I'm looking for and how to fix it, so I start working on the modification of our code and I'll send it to you when I have it.

Surely this also needs to be fixed for the non-core package editing view.

**Comment by Valc** [comment] 2021-08-30 22:43
@infograf768 
PR here
https://github.com/infograf768/j4localise/pull/17

**Comment by infograf768** [comment] 2021-09-01 10:02
Other bug.
The filtering for languages as well as Translations is always displaying all languages and not languages depending on the client.

This was working right in former versions for 3.x as we were using select in the Language field. This is no more the case:
```
$app  = JFactory::getApplication();
		$state = $app->getUserState('com_localise.select');
[...]
		// Listing languages in the language filter depending on the client filter
		if ($state && $state['client'] == 'installation')
		{
			$languages = $install;
		}
		elseif ($state && $state['client'] == 'administrator')
		{
			$languages = $admin;
		}
		elseif ($state && $state['client'] == 'site')
		{
			$languages = $site;
		}
		else
		{
			$languages  = array_merge($admin, $site, $install);
		}
```
In this version for 4.x this has been deleted and just replaced by `$languages  = array_merge($admin, $site, $install);`

Any idea to get the user state in the field?

**Comment by Valc** [comment] 2021-09-01 15:53
> Other bug.
> The filtering for languages as well as Translations is always displaying all languages and not languages depending on the client.

I will take a look ASAP.
Reegards

**Comment by Valc** [comment] 2021-09-01 21:37
@infograf768 
> Other bug.
> The filtering for languages as well as Translations is always displaying all languages and not languages depending on the client.

I think is solved :)

Basically to start, I have entered the file and added the `$app = Factory::getApplication();`

and just below one of my "die (var_dump($app->getUserState ('com_localise')));"

To see what came out of there, and it was this:

![die1](https://user-images.githubusercontent.com/417247/131746627-17635652-28d6-4d09-87d5-a9f1df04783e.png)

Now seems easy to resolve:

```
die (var_dump($app->getUserState ('com_localise.translations')));
die (var_dump($app->getUserState ('com_localise.translations.filter')));
die (var_dump($app->getUserState ('com_localise.translations.filter.storage')));
```

due each point is catching the data we are calling.

So, if we only needs the client value:

die(var_dump($app->getUserState('com_localise.translations.client')));

Also note that at the translations model the "populate state" function had alrready created that data.

Test it and if for you ok, please, make the PR

```
<?php
/**
 * @package     Com_Localise
 * @subpackage  models
 *
 * @copyright   Copyright (C) 2005 - 2015 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
namespace Joomla\Component\Localise\Administrator\Field;

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Filesystem\Folder;
use Joomla\CMS\Form\Field\ListField;
use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\LanguageHelper;
use Joomla\CMS\Language\Text;
use Joomla\Utilities\ArrayHelper;

FormHelper::loadFieldClass('list');

/**
 * Renders a list of all languages
 * Use instead of the joomla library languages element, which only lists languages for one client
 *
 * @package     Extensions.Components
 * @subpackage  Localise
 *
 * @since       1.0
 */
class LanguageField extends ListField
{
	/**
	 * The field type.
	 *
	 * @var    string
	 */
	protected $type = 'Language';


	/**
	 * Method to get the field input.
	 *
	 * @return  string    The field input.
	 */
	protected function getOptions()
	{
		// Initialise variables.
		$app            = Factory::getApplication();
		$filteredclient = $app->getUserState('com_localise.translations.client');

		$attributes = '';

		if ($v = (string) $this->element['onchange'])
		{
			$attributes .= ' onchange="' . $v . '"';
		}

		$params    = ComponentHelper::getParams('com_localise');
		$reference = $params->get('reference', 'en-GB');
		$admin     = LanguageHelper::getKnownLanguages(LOCALISEPATH_ADMINISTRATOR);
		$site      = LanguageHelper::getKnownLanguages(LOCALISEPATH_SITE);

		if (Folder::exists(LOCALISEPATH_INSTALLATION))
		{
			$install = LanguageHelper::getKnownLanguages(LOCALISEPATH_INSTALLATION);
		}
		else
		{
			$install = array();
		}

		if (!empty($filteredclient) && $filteredclient == 'installation')
		{
			$languages = $install;
		}
		elseif (!empty($filteredclient) && $filteredclient == 'administrator')
		{
			$languages = $admin;
		}
		elseif (!empty($filteredclient) && $filteredclient == 'site')
		{
			$languages = $site;
		}
		else
		{
			$languages  = array_merge($admin, $site, $install);
		}

		$attributes .= ' class="' . (string) $this->element['class'] . ($this->value == $reference ? ' iconlist-16-reference"' : '"');

		foreach ($languages as $i => $language)
		{
			$languages[$i] = ArrayHelper::toObject($language);
		}

		ArrayHelper::sortObjects($languages, 'name');
		$options = array();

		foreach ($this->element->children() as $option)
		{
			$options[] = HTMLHelper::_('select.option', $option->attributes('value'), Text::_(trim($option)), array('option.attr' => 'attributes', 'attr' => ''));
		}

		foreach ($languages as $language)
		{
			$options[] = HTMLHelper::_(
				'select.option',
				$language->tag,
				$language->name,
				array(
					'option.attr' => 'attributes',
					'attr' => 'class="' . ($language->tag == $reference ? 'iconlist-16-reference" title="'
						. Text::_('COM_LOCALISE_TOOLTIP_FIELD_LANGUAGE_REFERENCE') . '"' : '"'
					)
				)
			);
		}

		return $options;
	}
}
```

**Comment by infograf768** [comment] 2021-09-02 08:10
Beta 3 is available.
https://github.com/infograf768/j4localise/releases/tag/5.0.0-beta3

**Comment by infograf768** [comment] 2021-09-02 10:07
@Valc 
`$filteredclient = $app->getUserState('com_localise.translations.client');`

I guess $client may be enough, but this field is also used in Languages, not only in Translations.
Therefore we may have to check on which page we are and make a conditional.

something like
```
// Initialise variables.
		$app  = Factory::getApplication();
		$view = $app->input->get('view');

		if ($view === 'translations')
		{
			$client = $app->getUserState('com_localise.translations.client');
		}
		elseif ($view === 'languages');
		{
			$client = $app->getUserState('com_localise.languages.client');
		}
[...]

		// Listing languages in the language filter depending on the client filter
		if (!empty($client) && $client == 'installation')
		{
			$languages = $install;
		}
		elseif (!empty($client) && $client == 'administrator')
		{
			$languages = $admin;
		}
		elseif (!empty($client) && $client == 'site')
		{
			$languages = $site;
		}
		else
		{
			$languages  = array_merge($admin, $site, $install);
		}
```
The problem is that the Translations Language field keeps the same last list set in Languages language field.
Example: Languages filtering is done for installation in the languages views, the liste contains all installation languages.
Switching to Translations view, the list will always contain the same languages although the client filter may be sset to Site or Admin...

**Comment by infograf768** [comment] 2021-09-02 15:10
Maybe the solution is just to create a new field called `TranslationsLanguageField` as already done for client.

**Comment by Valc** [comment] 2021-09-02 15:28
@infograf768 
> Maybe the solution is just to create a new field called `TranslationsLanguageField` as already done for client.
> I tested that and it worked fine.

I was taking a look just now and i also think is the best option.

**Comment by Valc** [comment] 2021-09-02 15:31
> Beta 3 is available.
> https://github.com/infograf768/j4localise/releases/tag/5.0.0-beta3

Thank you :D

**Comment by infograf768** [comment] 2021-09-02 15:55
Merged
https://github.com/infograf768/j4localise/commit/191007471ccd2774faf0764ee8efc4120fc78459

**Comment by Valc** [comment] 2021-09-02 18:46
@infograf768 
> Merged

Care, JM: this one is now affected again by the field file names:

Using the file name "Translation**L**anguageField" the HMTL output for language tags field now is crashed.

Should be "TranslationslanguageField"

Within the file also should be:
```
class TranslationslanguageField extends ListField
{
	/**
	 * The field type.
	 *
	 * @var    string
	 */
	protected $type = 'Translationslanguage';
```

And then all will be working again

**Comment by infograf768** [comment] 2021-09-03 05:21
Hmm, does not crash here. And we have already `TranslationsClientField.php`, but, I will normalize.

**Comment by infograf768** [comment] 2021-09-03 06:13
Shall we release a beta4?

**Comment by Valc** [comment] 2021-09-03 06:21
> Shall we release a beta4?

Yep, please.

That about the name is really odd. The TranslationsClient field for me also was crashed, but not noticed at HTML output such as with TranslationsLanguage.

The stuff if that if i add one of my "die" when the file was called TranslationsClient it never ejec the die, only if i rename the file to standar name is died: so, i think is goood idea normalice them to avoid odd cases such the mine.

**Comment by infograf768** [comment] 2021-09-03 08:12
beta4 released

**Comment by Valc** [comment] 2021-09-04 20:58
Please, close. Now we are at beta 4 ;D

**Closed** 2021-09-22 09:47 UTC
