### ISSUE TITLE
PHP8 error when saving some ini files

### ISSUE THREAD

**Issue by fontanil** [infograf768/j4localise#42] opened 2021-10-21 16:51 UTC
Hi 
I'm trying to translate Akeeba Tickets System (com_ats.ini admin side) and I can't save the file, I get this message:
`0 The arguments array must contain 2 items, 1 given `
Debug and error reporting to maximum, there is one error when I open the list of files
`administrator/components/com_localise/Model/TranslationModel.php on line 317 (and line 321)`
I had no error with com_ats.sys.ini file.
Regards,
fontanil

Localise 5.0.0 beta 5
PHP 8.0.10

**Comment by infograf768** [comment] 2021-10-30 06:27
As @Bakual PR has been merged I will now directly add the `$field->addAttribute('translateLabel', 'false');` line in com_localise. It will not break php7 and will solve php8 for J4 next version.

@fontanil 
`line[0]` is never empty. If there are no comments starting with `;` then there are 2 possibilities, both are not boolean.

1. The first line of the file is blank, i.e. a return
In this case `line[0]` is equal to a space, i.e. " "

2 The first line is a string
`line[0]` = the first letter of the line constant i.e. "A" for example.

It is possible though that there is a problem with the end of file (eof) of one of your inis. In this case we could get a NULL because `$stream` would be wrong.

The only way to test is to edit one ini at a time after adding a var_dump line 316:
```
					while (!$stream->eof())
					{
						$line = $stream->gets();
						$lineNumber++;
					var_dump($line[0]);  //add this line
						if ($line[0] == '#')
						{
							$this->item->error[] = $lineNumber;
						}
						elseif ($line[0] == ';')
						{
```

**Comment by infograf768** [comment] 2021-10-30 06:33
Commit is here: https://github.com/infograf768/j4localise/commit/d88c552009f258a80efa253e20c7140ba74d663c

Thanks @Bakual

**Comment by fontanil** [comment] 2021-10-30 06:34
Sorry JM, but line[0] is empty on some lines and then an error occurs with PHP 8

**Comment by Valc** [comment] 2021-10-30 07:05
@infograf768 

https://downloads.joomla.org/technical-requirements

Seem Joomla 4 is PHP 8 Recommended

I will take a look  to mount at my descktop PC a test server  this weekend if i have time.

**Comment by Valc** [comment] 2021-10-30 15:04
@infograf768 
@fontanil

Now i am testing on PHP 8.0.12 with debug and error reporting to maximum using the package than JM have here:

https://github.com/infograf768/j4localise/issues/42#issuecomment-950283532

With the last one added to our pack:

https://github.com/infograf768/j4localise/issues/42#issuecomment-955159282

Also with the Bakuals' PR added to Joomla core files:

https://github.com/joomla/joomla-cms/pull/35900.

Due if not, the same issue that at PHP 7 was simply triggering a log warning, at PHP 8 make a crash than is not possible continue working with com_localise files edition in normal mode.

But, one time the previous issue due "blindly try to translate the formfield label" is solved, **i can not reproduce the  issue related with `$line[0]`**: no warnings, no log messages, nothing.

I think we need more testers due surely the issue is there, but if it is invisible for us seems there is no way to continue.

**Comment by fontanil** [comment] 2021-10-30 15:18
Please try this code
`					while (!$stream->eof())
					{
						$line = $stream->gets();
						$lineNumber++;
						if(empty($line[0])) {
							
						} else
						if ($line[0] == '#')
						{
							$this->item->error[] = $lineNumber;
						}
						elseif ($line[0] == ';')`
On my test site, PHP 8.0.8, no more error for line[0]

**Comment by Valc** [comment] 2021-10-30 15:21
@fontanil
I think we can solve adding that patch, but also is possible than this one is a PHP 8 bug than they have solved at my PHP released version. Note than they also have bug to fix:

https://www.php.net/ChangeLog-8.php

It is possible you text under the last PHP 8 version?

**Comment by fontanil** [comment] 2021-10-30 15:50
With PHP 8.0.12 on Wampserver 64, without my changes:
"Warning: Trying to access array offset on value of type bool in D:\wamp64\www\admtools\administrator\components\com_localise\Model\TranslationModel.php on line 319"
No more error with the code I quoted.

**Comment by Valc** [comment] 2021-10-30 15:53
And with the next code lines you have the warning??

```
					while (!$stream->eof())
					{
						$line = $stream->gets();
						$lineNumber++;

						if (!empty($line) && $line[0] == '#')
						{
							$this->item->error[] = $lineNumber;
						}
						elseif (!empty($line) && $line[0] == ';')
						{
```

**Comment by fontanil** [comment] 2021-10-30 15:59
No error with this code, as it is quite the same of mine. ;)
As I said some comments higher:
"I proposed to check if line[0] is empty and you added it in the code you quoted there__"

**Comment by Valc** [comment] 2021-10-30 16:03
Please, also test the next code than have an "if "empty" doing something :D
```
					while (!$stream->eof())
					{
						$line = $stream->gets();
						$lineNumber++;

						if (empty($line))
						{
							die("The line number $lineNumber is empty and the line[0] have the $line[0] value");
						}
						elseif ($line[0] == '#')
						{
							$this->item->error[] = $lineNumber;
						}
						elseif ($line[0] == ';')
						{
```

**Comment by fontanil** [comment] 2021-10-30 16:15
Warning: Trying to access array offset on value of type bool in D:\wamp64\www\admtools\administrator\components\com_localise\Model\TranslationModel.php on line 319

"**The line number 1 is empty and the line[0] have the value**

line[0] is empty so you can't display "the $line[0] value"

**Comment by Valc** [comment] 2021-10-30 16:19
> line[0] is empty so you can't display "the $line[0] value"
Yes, this one simply demonstrates that an empty line is not returning "false", "null", etc as $line[0] value.
But, what file are you editing? is there a empty line at "line 1"?

**Comment by fontanil** [comment] 2021-10-30 16:25
I don't know what file, it's the translation listing page for administrator french files.

**Comment by Valc** [comment] 2021-10-30 16:26
Arrrgh! all this one happens at translations view!! I have no tested there!

**Comment by Valc** [comment] 2021-10-30 17:02
I can not found files with errors at translations view and no log warnings.
Can you tests at translations view the next code lines, than will try to search the path to the file than at line 1 have an empty line?
```

					while (!$stream->eof())
					{
						$line = $stream->gets();
						$lineNumber++;

						if (empty($line) && $lineNumber == '1')
						{
							die("The line number $lineNumber is empty at this path: $path");
						}
						elseif ($line[0] == '#')
						{
							$this->item->error[] = $lineNumber;
						}
						elseif ($line[0] == ';')
						{
```

**Comment by fontanil** [comment] 2021-10-30 17:23
The line number 1 is empty at this path: D:\wamp64\www\admtools\administrator/language/en-GB/plg_console_admintools.ini

This file is empty
(I'm trying to translate Admin Tools, Akeeba backup and Akeeba Tickets System)

**Comment by Valc** [comment] 2021-10-30 17:26
Ok, surely if we have an empty file we will get the same error.

But this ones is an error perse to handle. So, i suggest add some code control than is the file to translate is empty, alarm about it.

**Comment by infograf768** [comment] 2021-11-01 07:00
Do I understand well  that the reference language (en-GB) ini file was totally empty i.e. not even a return?
`D:\wamp64\www\admtools\administrator/language/en-GB/plg_console_admintools.ini`

If that is the case, indeed we have an empty `line[0]`.

@Valc 

I think this would rarely happen. But we should throw an error indeed with a new string.

String (I don't think we need to test and display line[1]):
COM_LOCALISE_ERROR_FILE_EMPTY="This reference file is empty: %s"

Code:
```
						$line = $stream->gets();
						$lineNumber++;

						if (empty($line))
						{
							$emptyFile = str_replace(JPATH_ROOT, '', $path);
							Factory::getApplication()->enqueueMessage(Text::sprintf('COM_LOCALISE_ERROR_FILE_EMPTY', $emptyFile), 'error');
						}
						elseif ($line[0] == '#')
						{
							$this->item->error[] = $lineNumber;
						}
						elseif ($line[0] == ';')
etc.
```

I deleted the contents of com_actionlogs.ini
<img width="1405" alt="Screen Shot 2021-11-01 at 07 49 20" src="https://user-images.githubusercontent.com/869724/139633193-2b4220a5-f2f8-4b99-9506-5d4b2048fe91.png">

What do you think?

**Comment by Valc** [comment] 2021-11-01 07:36
@infograf768
Yes, seems than all the issue is due "empty files", so, no matter the PHP version.

It were invisible for us due no empty files in our case.

With the en-GB empty of content have no sense try to count or catch errors, keys, etc, and the same for the xx-XX file to translate.

I think than we need throw an error such as you have done, but we need catch and stop the issue at first moment it is detectable and then:

1. Display the issued file from translations view list.
2. Disable "normal mode" edition to that issued file from translations view list.
3. Allow only raw mode edition from translations view list so we can to try to solve the issued file adding strings to handle.

How is displayed after your patch? D
Due is posible than by actual code this one is already under control when a file with "error" is catched.
If not we also can try:

```
if (empty($line))
						{
                                                        // Adding a parse error to line 0 (not 1) due using 0 maybe we can handle from other code parts the isse when the error is at line 0
                                                        $this->item->error[] = 0;
							$emptyFile = str_replace(JPATH_ROOT, '', $path);
							Factory::getApplication()->enqueueMessage(Text::sprintf('COM_LOCALISE_ERROR_FILE_EMPTY', $emptyFile), 'error');
						}
```
If working we does not need to search other code locations to prevent the issue or other issues than can jump due empty file.

**Comment by infograf768** [comment] 2021-11-01 08:42
> Allow only raw mode edition from translations view list so we can to try to solve the issued file adding strings to handle.

I am not sure this makes sense. The problem is in the reference file. If one has an empty reference, what is the use of a translation using raw? It just would not be a translation.

Imho we should not be able to click at all to edit the non-reference file in this case in the translations view.
Better yet, maybe we should not display it at all.

**Comment by Valc** [comment] 2021-11-01 08:54
Yes, JM you are right: what sense have use empty reference files? for me have no one too.
But, as you say, this would rarely happen (my forst time in all this years :D )
One time the issue can happen, only one way to solve it from our code side is opended:

Add the missing content to the empty file by raw mode edition or be unable to handle that file as is usual. No matter is the empty file is en-GB or at xx-XX reference language. My test is at xx-XX language.

If we make the case "invisible" or "unaccessible", then the user need to search the emprty file at server and solve the issue adding content: we can help there in a more controlable way to edit and save files at raw mode edition.

**Comment by fontanil** [comment] 2021-11-01 09:11
A note: add an empty line at the beginning of a reference file, and you get an empty $Line[0] and a warning on PHP 8
Try with com_actionlogs.ini for example.

So you must be sure the file is really empty and not only its first line if you don't want to display it.

**Comment by Valc** [comment] 2021-11-01 11:35
> A note: add an empty line at the beginning of a reference file, and you get an empty $Line[0] and a warning on PHP 8 Try with com_actionlogs.ini for example.
> 
> So you must be sure the file is really empty and not only its first line if you don't want to display it.

yes, i think is posible take a look about if the file is empty with similar code to:

`if (is_null($stream->get('filesize'))`

But, Add "empty lines as first line" seems again an not expected behaivor to handle: doing that one within xml files will trigger crashes for sure due is not allowed. Not sure if is valid or not at ini files, but seems than is not the expected format to use, so, I think we also need to take a look there.

Now i think we are close to catch the bug due this one is not what it seems:

@infograf768
@fontanil

Are you able to edit some file content `in raw mode edition` with `"en-GB" `language selected files that are 3pd or `non core file`s?

Me no.

**Comment by infograf768** [comment] 2021-11-02 07:40
Hmm

> A note: add an empty line at the beginning of a reference file, and you get an empty $Line[0] and a warning on PHP 8
Try with com_actionlogs.ini for example.

Not here. The line is not empty. It contains a Return. In this case, as I wrote above, $line[0] equals to a space. easy way: var_dump($line[0] ); die; and you get " "

**Comment by fontanil** [comment] 2021-11-02 07:51
With PHP 8, you get a warning and this warning is no more displayed if you check if $line[0] is empty

**Comment by infograf768** [comment] 2021-11-02 08:55
If you have a return, no more warning. as I explained. 
Just edit an empty file (here com.actionslog.ini) and check when it contains a return or nothing at all.
![emptyline](https://user-images.githubusercontent.com/869724/139814528-5e0bb53a-95f4-4647-a04f-a1041952a390.gif)

If you display the whole translations view, delete the `die;` but it is more confusing to see exactly what happens.

**Comment by infograf768** [comment] 2021-11-06 10:34
See https://github.com/infograf768/j4localise/pull/45

**Closed by infograf768** 2021-11-06 10:34 UTC
